source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LKMediaManager', :exclusive => true do
  pod "LKMediaManager", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "LKMediaManager", :path => "../"

  
end
