source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LKMediaManager' do
  pod "LKMediaManager", :path => "../"
end

target 'Tests' do
  pod "LKMediaManager", :path => "../"


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |configuration|
      configuration.build_settings['SWIFT_VERSION'] = '3.0'
    end 
  end 
end
  
end
